services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql:3306/swiftcodes
      - spring.datasource.username=springstudent
      - spring.datasource.password=springstudent
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      - mynetwork
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_ROOT_PASSWORD: springstudent
      MYSQL_DATABASE: swiftcodes
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
